### ISSUE TITLE
Docker SDK doesn't work if Docker Desktop is shut down

### ISSUE THREAD

**Issue by bwateratmsft** [docker-archive-public/docker.node-sdk-legacy#31]
@BigMorty found this the other day.

Repro steps:

1. Create an ACI context
1. Run a container in the ACI context
1. Shut down Docker Desktop
1. Doing `docker ps` on the command line works, the above container is shown

Expected:
The SDK also works since it shouldn't need Docker Desktop running to talk to ACI

Actual:
The SDK throws an error, `14 UNAVAILABLE: No connection established`

Is the SDK daemon lifecycle tied to Docker Desktop?

**Comment by gtardif** [comment]
Indeed, the lifecycle of the SDK (command `docker serve <URL>`) is managed by Docker Desktop on mac/windows. 
This was discussed specifically in https://github.com/docker/desktop-microsoft/issues/8, we agreed it was better to have Desktop managing this lifecycle, rather than requiring VSCode to start/stop the serve command. 

Note that there are also some ACI features that sometimes require the docker engine to be up. The ACR auto login for example requires a `docker login myacrregistry`, which is performed on the engine side ; this will also be tight to the lifecycle of Docker Desktop.

**Comment by bwateratmsft** [comment]
Good to know. Agree that we'd prefer that VSCode not need to manage starting/stopping this.

What does the CLI do differently that allows it to still work for at least some things?

**Comment by rumpl** [comment]
The CLI doesn't use the gRPC API to talk to the ACI backend, it calls it directly.
